plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    namespace 'com.ads.nkh'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.14.0'

    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation "androidx.lifecycle:lifecycle-runtime:2.10.0"

    // Admob
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.gms:play-services-ads:25.3.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.3.0'

    implementation "com.android.billingclient:billing:9.0.0"
    implementation "com.google.guava:guava:33.6.0-android"

    implementation 'com.google.firebase:firebase-analytics:23.2.0'

    // Mediation
    implementation 'com.google.ads.mediation:facebook:6.21.0.3'
    implementation 'com.google.ads.mediation:applovin:13.6.2.0'
    implementation 'com.google.ads.mediation:vungle:7.7.4.0'
    implementation 'com.google.ads.mediation:pangle:8.0.0.5.0'
    implementation 'com.google.ads.mediation:mintegral:17.1.61.0'
    implementation 'com.unity3d.ads:unity-ads:4.18.1'
    implementation 'com.google.ads.mediation:unity:4.18.0.0'
    implementation 'com.google.ads.mediation:ironsource:9.4.2.0'

    // Facebook SDK
    implementation 'com.facebook.android:facebook-android-sdk:18.2.3'

    // Adjust
    implementation 'com.adjust.sdk:adjust-android:5.7.0'
    implementation 'com.android.installreferrer:installreferrer:2.2'

    // Lottie
    implementation 'com.airbnb.android:lottie:6.7.1'

    // Sdp & Ssp
    implementation 'com.intuit.sdp:sdp-android:1.1.1'
    implementation 'com.intuit.ssp:ssp-android:1.1.1'
}

afterEvaluate {
    publishing {
        publications {
            create("release", MavenPublication) {
                from(components["release"])
                groupId = "com.github.trongluan99"
                artifactId = "NKH-Studio"
                version = "1.0.0"
            }
        }
    }
}
